### PR TITLE
Roll back impl core::error::Error

### LINKED ISSUE #992: Compilation error with url 2.5.3 / idna 1.0.3 with Rust < 1.81 and edition 2021 (resolver 2) when sqlx-core < 0.8.3 is in the dependency graph
Edited by @hsivonen to put resolution options at the top for folks who come here:

__To resolve this compilation error, update SQLx to 0.8.3 and/or update Rust to 1.81 or later.__

This compilation error is due to a combination of:
1. SQLx unnecessarily turning off the default features of `url`, and from a proc macro context specifically. (Request for SQLx not to do that: https://github.com/launchbadge/sqlx/issues/3589)
2. `url` 2.5.3 (and `idna` 1.0.3) conditionally raising MSRV to 1.81 when default features are off (from #831). Conditionally raising MSRV to 1.81 is not a semver break, because raising MSRV isn't a semver break.
3. `resolver = "2"`, which is implied by `edition = "2021"` performing feature resolution for proc macro dependencies separately from normal dependencies, so a normal dependency on `url` with default features enabled does not cause default features to be enabled for the proc macro case.

Original report follows:
----

- [x] Note that this crate implements the [URL Standard](https://url.spec.whatwg.org/) not RFC 1738 or RFC 3986

**Describe the bug**

After update to v1.0.3 wich is picked up automatically since its a patch upgrade, our code no longer compiles the same. 

rust versions tested: 
* rustc 1.80.1
* rustc 1.81.0

```
   Compiling idna v1.0.3
error[E0658]: use of unstable library feature 'error_in_core'
  --> /home/krille/.cargo/registry/src/index.crates.io-6f17d22bba15001f/idna-1.0.3/src/lib.rs:78:6
   |
78 | impl core::error::Error for Errors {}
   |      ^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #103765 <https://github.com/rust-lang/rust/issues/103765> for more information
   ```

### PR DESCRIPTION
**Pull request by hsivonen**
Fixes #992.

### CODE REVIEW

**Comment by hsivonen** [comment]
Need to verify that this actually makes things work with `sqlx-core` in the depedency graph on Rust < 1.81.

**Comment by hsivonen** [comment]
The failure for `sqlx-core`'s `url` and `idna` to unify with the top level's interferes with testing this with a git override locally!

**Comment by lo48576** [comment]
Sorry for necrobumping, but shouldn't this be fixed on `idna` crate side?

Documentation says that `idna` requires `alloc` feature (but not `std`) and MSRV in Cargo.toml is still 1.57, so this crate fails to compile with a valid configuration.

```
$ git rev-parse HEAD
a66f4220895c3cc84ae623c218466710eb3a812f
$ cargo +nightly update -Z minimal-versions
...
$ cargo +1.60 check --no-default-features --features=alloc,compiled_data
    Checking idna v1.1.0 (/home/nopth/src/open/dev/_contrib/rust-url/idna)
error[E0433]: failed to resolve: could not find `error` in `core`
  --> idna/src/lib.rs:78:12
   |
78 | impl core::error::Error for Errors {}
   |            ^^^^^ could not find `error` in `core`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `idna` due to previous error
```

[`core::error`](https://doc.rust-lang.org/1.81.0/core/error/index.html) is stabilized since Rust 1.81.0, so if `idna` supports "no-std" (but `alloc` enabled), this should compile.
