### ISSUE TITLE
Compilation error with url 2.5.3 / idna 1.0.3 with Rust < 1.81 and edition 2021 (resolver 2) when sqlx-core < 0.8.3 is in the dependency graph

### ISSUE THREAD

**Issue by TotalKrill** [servo/rust-url#992]
Edited by @hsivonen to put resolution options at the top for folks who come here:

__To resolve this compilation error, update SQLx to 0.8.3 and/or update Rust to 1.81 or later.__

This compilation error is due to a combination of:
1. SQLx unnecessarily turning off the default features of `url`, and from a proc macro context specifically. (Request for SQLx not to do that: https://github.com/launchbadge/sqlx/issues/3589)
2. `url` 2.5.3 (and `idna` 1.0.3) conditionally raising MSRV to 1.81 when default features are off (from #831). Conditionally raising MSRV to 1.81 is not a semver break, because raising MSRV isn't a semver break.
3. `resolver = "2"`, which is implied by `edition = "2021"` performing feature resolution for proc macro dependencies separately from normal dependencies, so a normal dependency on `url` with default features enabled does not cause default features to be enabled for the proc macro case.

Original report follows:
----

- [x] Note that this crate implements the [URL Standard](https://url.spec.whatwg.org/) not RFC 1738 or RFC 3986

**Describe the bug**

After update to v1.0.3 wich is picked up automatically since its a patch upgrade, our code no longer compiles the same. 

rust versions tested: 
* rustc 1.80.1
* rustc 1.81.0

```
   Compiling idna v1.0.3
error[E0658]: use of unstable library feature 'error_in_core'
  --> /home/krille/.cargo/registry/src/index.crates.io-6f17d22bba15001f/idna-1.0.3/src/lib.rs:78:6
   |
78 | impl core::error::Error for Errors {}
   |      ^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #103765 <https://github.com/rust-lang/rust/issues/103765> for more information
   ```

**Comment by valenting** [comment]
@TotalKrill 
Is your crate depending on idna directly with default-features = false.
Or is the issue url failing to propagate the std feature to idna?

**Comment by TotalKrill** [comment]
We are depending on url, not idna directly

**Comment by TotalKrill** [comment]
@valenting seems i was wrong about 1.81.0, seems to work there...

**Comment by hsivonen** [comment]
Are you depending on `url` with `default-features = false`?

I tried to repro on 1.80.1, and the following compiles:
````sh
rustup default 1.80
cargo new --bin testurl
cd testurl
cargo add url
cargo build



```

**Comment by TotalKrill** [comment]
we have a workspace, but we only depend on url like this: `url = "2.5.0"`

**Comment by TotalKrill** [comment]
running `cargo tree -i url -f "{p} {f}"` 

this is what our tree ends up looking like, with two different versions of URL included, probably by one of our other deps.

- url v2.5.0 default,serde,std
- url v2.5.0

**Comment by hsivonen** [comment]
`url` 2.5.0 and `url` 2.5.2 depended on `idna` 0.5. `url` 2.5.1 depended on `idna` 1.0.

The introduction of `no_std` support to `url` in 2.5.3 and the introduction of `core::error::Error` to `idna` in 1.0.3 was intended not to change MSRV to 1.81 with default features but was expected to change MSRV to 1.81 for `default-features = false` users.

Do you somehow have `url` 2.5.1 in your dependency graph? Can you force Cargo to take `url` 2.5.3 in its place?

**Comment by TotalKrill** [comment]
Oh sorry, I am currently forcing our software to take 2.5.0, since 2.5.3 does not compile. Updated the previous comment to show that the cargo tree command showed 2.5.3

**Comment by hsivonen** [comment]
So if you have `url` 2.5.3 without features and `url` 2.5.3 with the feature `std`, Cargo should unify those to one copy of `url` with the feature `std`. Are you sure the edited comment about `cargo tree` is correct?

(Aside: This isn't specific to idna. If I use Rust 1.80.1 with:

````toml
[dependencies]
url = { version = "2.5.3", default-features = false }
idna = "1"
````

...`idna` compiler and the compilation of `url` fails with a complaint about `impl core::error::Error for ParseError {}` in `url`.

**Comment by TotalKrill** [comment]
yep, my edited comment stands. But with what you say, something else might be changing to `default-features = false`

**Comment by hsivonen** [comment]
As long as something in your dependency graph depends on `url` without setting `default-features = false`, something else setting `default-features = false` shouldn't matter.

@Twixes, GitHub autolinks a couple of your changesets referencing this issue. Do you have minimized steps to reproduce?

**Comment by valenting** [comment]
I think `cargo tree -e features` might explain if there's such a dependency conflict.

**Comment by mental32** [comment]
Just felt this through my direct dependency to `sqlx`. I'm commenting here but I'm not sure who, sqlx or idna, is responsible in this case. (@hsivonen would appreciate your take here)

minimal verifiable example:

```
cd /tmp
cargo new idna-992-repro
cd idna-992-repro/
cargo add sqlx
cargo check
```

And I get the same compilation error as @TotalKrill

The latest version of SQLx is `v0.8.2` in the example, but in my original encounter its `v0.7.4`

<details>

<summary>cargo --version --verbose</summary>


```
cargo 1.80.1 (376290515 2024-07-16)
release: 1.80.1
commit-hash: 37629051518c3df9ac2c1744589362a02ecafa99
commit-date: 2024-07-16
host: aarch64-apple-darwin
libgit2: 1.7.2 (sys:0.18.3 vendored)
libcurl: 8.7.1 (sys:0.4.72+curl-8.6.0 system ssl:(SecureTransport) LibreSSL/3.3.6)
ssl: OpenSSL 1.1.1w  11 Sep 2023
os: Mac OS 15.0.1 [64-bit]
```

</details>

<details>

<summary>rustc --version --verbose</summary>

```
rustc 1.80.1 (3f5fd8dd4 2024-08-06)
binary: rustc
commit-hash: 3f5fd8dd41153bc5fdca9427e9e05be2c767ba23
commit-date: 2024-08-06
host: aarch64-apple-darwin
release: 1.80.1
LLVM version: 18.1.7
```
</details>

**Comment by hsivonen** [comment]
> As long as something in your dependency graph depends on `url` without setting `default-features = false`, something else setting `default-features = false` shouldn't matter.

Interestingly, this turns out not to be true.

````sh
rustup default 1.80
cargo new idna-992-repro
cd idna-992-repro/
cargo add sqlx
cargo add url
cargo check
````

Still fails. (Not the added `cargo add url`.)

@domenukk why does `sqlx-core`'s dependency on `url` with `default-features = false` does not unify with the top-level's dependency on `url` (with default features)?

**Comment by TotalKrill** [comment]
We are also using sqlx, so might be through that

**Comment by hsivonen** [comment]
`sqlx-core` has `url = { version = "2.2.2", default-features = false }`. How has that not failed due to `url` requiring `alloc` before?

**Comment by Twixes** [comment]
@hsivonen I pinned `idna` to `0.5` in Cargo.toml's `[dependencies]` – seems to solve the issue. It also appears to be stemming from sqlx for us

**Comment by hsivonen** [comment]
> @hsivonen I pinned `idna` to `0.5` in Cargo.toml's `[dependencies]` – seems to solve the issue. 

How do you mean https://github.com/PostHog/posthog/commit/5f6e5d1100e42cf099ec881fa6203e13fc0bc2f6 fixed it for you? That's _really_ weird. By what mechanism should that help?

**Comment by Twixes** [comment]
Actually you are right, the `Cargo.toml` change doesn't help. It's the `--locked` arg of `cargo install` that's _the_ fix.

For us, the issue was with this command: `cargo install sqlx-cli@0.7.3 --no-default-features --features native-tls,postgres`. Used to work with Rust 1.77, but starting today it only works on 1.81+ – because of `idna` 1.0 getting installed. Our lockfile _has_ already been specifying `idna` 0.5 though.

By appending `--locked` to `cargo install sqlx-cli@0.7.3 --no-default-features --features native-tls,postgres` we make it so that the lockfile is respected, fixing installation. (It looks like there's no alternative way to restrict transitive dependencies in `cargo install`)

**Comment by hsivonen** [comment]
The sqlx change that added `default-features = false` was https://github.com/launchbadge/sqlx/commit/d76b1357da21f777ee1cdab8bfd907ed66c7b3bd#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R62 which doesn't explain why.

**Comment by hsivonen** [comment]
Filed an sqlx issue: https://github.com/launchbadge/sqlx/issues/3589

**Comment by domenukk** [comment]
> > As long as something in your dependency graph depends on `url` without setting `default-features = false`, something else setting `default-features = false` shouldn't matter.
> 
> Interestingly, this turns out not to be true.
> 
> ```shell
> rustup default 1.80
> cargo new idna-992-repro
> cd idna-992-repro/
> cargo add sqlx
> cargo add url
> cargo check
> ```
> 
> Still fails. (Note the added `cargo add url`.)
> 
> @domenukk why does `sqlx-core`'s dependency on `url` with `default-features = false` not unify with the top-level's dependency on `url` (with default features)?

Have you figured that one out? I feel like it _should_? Different versions of the `url` crate?

**Comment by hsivonen** [comment]
> > > As long as something in your dependency graph depends on `url` without setting `default-features = false`, something else setting `default-features = false` shouldn't matter.
> > 
> > 
> > Interestingly, this turns out not to be true.
> > ```shell
> > rustup default 1.80
> > cargo new idna-992-repro
> > cd idna-992-repro/
> > cargo add sqlx
> > cargo add url
> > cargo check
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Still fails. (Note the added `cargo add url`.)
> > @domenukk why does `sqlx-core`'s dependency on `url` with `default-features = false` not unify with the top-level's dependency on `url` (with default features)?
> 
> Have you figured that one out?

I have not.

> I feel like it _should_?

I agree. Could this be a Cargo bug? The unusual thing that I notice is that the `sqlx-*` dependencies within the `sqlx` suite of crates are exact version dependencies. However, when `sqlx-core` and `sqlx-macros-core` depend on `url` 2.2.2 (not an exact-version dependency) with `default-features = false`, the crate does get upgraded to 2.5.3 by Cargo.

Can an exact version dependency up the graph from `url` confuse feature unioning in Cargo even when it does not confuse version upgradeability?

> Different versions of the `url` crate?

No, `Cargo.lock` shows only one instance of `url` 2.5.3.

**Comment by hsivonen** [comment]
Posted a request for help with figuring out why Cargo is doing what it does:
https://users.rust-lang.org/t/why-doesnt-cargo-compile-with-a-union-of-features/120716

**Comment by Manishearth** [comment]
> but strictly speaking we're being good citizens by doing this.

I see where you're coming from, but I also slightly disagree: I think it's pretty much a norm for crates to assume that splitting out code into a feature but including it in default is not a breaking change, so in this case you're open to breakages.

It's a tradeoff. There have been proposals for being able to say which version your feature spec is based on.

**Comment by Manishearth** [comment]
> It's a really weird situation that disabling a feature leads to an increase in the MSRV

I also feel like this at least used to be somewhat expectable back in the days when no_std was not as polished. But I haven't seen that in ages.

**Comment by hsivonen** [comment]
(I edited the issue description to put solutions at the top of the page at this point in the thread.)

**Comment by hsivonen** [comment]
Update: [The removal of `default-features = false` for `url` has been merged to `sqlx` trunk](https://github.com/launchbadge/sqlx/pull/3601). Leaving this issue open for people to find still, since there hasn't been an sqlx release with that changeset, yet.

**Comment by hsivonen** [comment]
> Perhaps a couple of weeks is enough and then we can close this.

It's been more than a couple of weeks.
