### ISSUE TITLE
idna: unable to compile with declared MSRV

### ISSUE THREAD

**Issue by barower** [servo/rust-url#1110]
- [ ] Note that this crate implements the [URL Standard](https://url.spec.whatwg.org/) not RFC 1738 or RFC 3986

**Describe the bug**
When trying to compile my project with an older Rust version (1.74.1), I've stumbled on this error:

```
$ cargo +1.74.1 build
   ...
   Compiling icu_normalizer v1.5.0
   Compiling idna_adapter v1.2.0
   Compiling idna v1.1.0
error[E0658]: use of unstable library feature 'error_in_core'
  --> /home/bosinski/.cargo/registry/src/index.crates.io-6f17d22bba15001f/idna-1.1.0/src/lib.rs:78:6
   |
78 | impl core::error::Error for Errors {}
   |      ^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #103765 <https://github.com/rust-lang/rust/issues/103765> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `idna` (lib) due to previous error
```

In `idna` v1.1.0 [declared MSRV is 1.57](https://github.com/servo/rust-url/blob/main/idna/Cargo.toml#L11C1-L11C51), but [`core_in_error` has only been stable starting from 1.81](https://releases.rs/docs/1.81.0/#stabilized-apis)

**Comment by hsivonen** [comment]
It should build on 1.57 in you enable the `std` feature for `idna`, downgrade `idna_adapter` to 1.1.0, and downgrade `libc` to whatever version still supported 1.57.

Does that not work?
